version: '3.1'
services:
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - USER_ID=${UID}
        - GROUP_ID=${GROUPS}
    environment:
      HOST: '0.0.0.0'
      NODE_ENV: development
    command: bash -c "npm install && npm run dev -L"
    working_dir: /app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - USER_ID=${UID}
        - GROUP_ID=${GROUPS}
    command: bash -c "npm install && npm start -L"
    working_dir: /app
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /app/node_modules
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
      - '28017:28017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - 'mongo:/data/db'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - './db/redis:/data'
volumes:
  mongo: {}
